[cookie]
expiry_days = 30
key = "some_random_secret_key"
name = "meals_app_cookie"

[credentials.usernames.user1]
name = "UserOne"
password = "$2b$12$jVvEIPL0DOdA7lCUZ8X6MuDSB0ZpFZzAva9FCAOCVZms7SvfWY4lS"
email = "user1@gmail.com"

[credentials.usernames.user2]
name = "UserTwo"
password = "$2b$12$8RaB893v4G3M/lyAZOH4vuob1PzZzA26eA7Xe./UR63hhPEEgagMG"
email = "user2@gmail.com"

preauthorized = ["someone@gmail.com", "another_user@gmail.com"]

[SUPABASE]
url = "https://mxnexzqewechhhxahuaf.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14bmV4enFld2VjaGhoeGFodWFmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzAwMTAwNSwiZXhwIjoyMDcyNTc3MDA1fQ.s7_8UaNaSaPePfg59Bmhs1xwV2rd-6iHeWVaEbbGl24"
